apiVersion: v1
kind: Namespace
metadata:
  name: backend
---
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-web
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: golang-web
    spec:
      containers:
      - name: hello-app
        image: <IMAGE>
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 50m
          limits:
            cpu: 50m
---
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: backend
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: golang-web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-web
  namespace: backend
  annotations:
    cert-manager.io/issuer: letsencrypt-nginx
spec:
  tls:
    - hosts:
      - web.giuliohome.org
      secretName: letsencrypt-nginx-web
  rules:
    - host: web.giuliohome.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80
  ingressClassName: nginx
