apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-golang-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke-golang-web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: gke-golang-web
    spec:
      imagePullSecrets:
       - name: do-registry
      containers:
      - name: hello-app
        image: registry.digitalocean.com/giulio/golang-web:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 50m
          limits:
            cpu: 50m
---
apiVersion: v1
kind: Service
metadata:
  name: gke-golang-web-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: gke-golang-web
